FROM golang:1.22-alpine3.19 as builder

WORKDIR /app
COPY . .
RUN go build -o /go/bin/test-api ./cmd/main.go

FROM scratch
COPY --from=builder /go/bin/test-api /go/bin/test-api
ENTRYPOINT ["/go/bin/api"]